name: test-integration

on:
  workflow_run:
    workflows: [test-unit]
    branches: [master]
    types: [completed]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'local_store'
        mysql root password: 'root'

    - name: Install grpcurl
      run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v1.8.2

    - name: Build store service
      uses: gradle/gradle-build-action@v2
      with:
        arguments: bootJar

    - name: Run store service and integration test
      run: |
        . scripts/env-local && sudo -E java -jar build/libs/store-v1.jar &
        sleep 30s
        scripts/test-http-server.sh
        scripts/test-grpc-server.sh